### ISSUE TITLE
Deno Extension on by default in non deno project

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/vscode_deno#1048]
**Describe the bug**

Deno Extension is on by default in project without deno config file (only `package.json`).
All setting are default.  No addition deno setting in `settings.json` (global or workspace)

If I disable it explicitly, it solves the issue. But i expect that deno extansion shouldn't work in such case by default.
```json
{
   "deno.enable": false
}
```

**Versions**

vscode: 1.85.2 deno: 1.40.0 extension: 3.33.2

**Comment by nayeemrmn** [comment]
@shevernitskiy When you hover something, do you get intellisense from both the node TS server and Deno, or just Deno? For example if you hover a symbol do you see the same content twice?

**Comment by shevernitskiy** [comment]
I see content once in both cases - deno.enable true/false. When it's true it also point at incorrect import pathes (because without file extension). But in case of undifined or null deno.enable, it shows no any intellisense on symbol and any erros for import pathes.

**Comment by SkepticMystic** [comment]
This sounds like the same underlying issue I'm experiencing. VS Code automatically updated to the latest deno extenstion release earlier today.  Since then, TS intellisense has not worked at all. I don't get any content on hover. I noticed this in a Node project.

The output tab for Typescript gives a `[error] TSServer exited. Code: null. Signal: SIGTERM` error, then tries to restart 5 times before giving up. _Sometimes_ the error is `[error] TSServer errored with error. A system error occurred (write EPIPE)`, but I can't reproduce that.

VS Code recommended disabling extensions before reporting the issue. It specifically mentioned disabling the Deno and Svelte extensions, presumably because they override TS intellisense. After disabling Deno, intellisense is back, with all other extensions enabled.

Some specs: I'm running VS Codium 1.85.1, with the latest Deno extension version, release a few hours ago.
Please let me know if there is more info I can provide.

**Comment by nayeemrmn** [comment]
@SkepticMystic That's a separate issue that's been addressed, please upgrade to the latest version

**Comment by SkepticMystic** [comment]
Alright. VS Codium doesn't see the new version yet, but I will try again tomorrow. Thanks!
