### ISSUE TITLE
Add autocomplete for https imports

### ISSUE THREAD

**Issue by brandonkal** [denoland/vscode_deno#107]
This is a pain point with using Deno. Naturally the cache layout makes this very difficult for all tools.

**Comment by buttercubz** [comment]
> This is a pain point with using Deno. Naturally the cache layout makes this very difficult for all tools.

take a look at [this](https://github.com/crewdevio/Trex), I think it can help you

**Comment by brandonkal** [comment]
That's a neat little utility but import maps are still unstable and even so, it doesn't provide autocomplete.

**Comment by CGQAQ** [comment]
@brandonkal Hope #172 will help you

**Comment by lucacasonato** [comment]
@brandonkal We autocomplete already cached files from "DENO_DIR" now, and we have full IntelliSense for deno.land/x (https://www.reddit.com/r/Deno/comments/imitln/the_vs_code_deno_extension_now_has_intellisense/). I hope support for nest.land URLs will come soon. Does this solve the scope of the issue somewhat?

**Comment by brandonkal** [comment]
Can we standardize on a generic autocomplete solution? Like a sitemap file at the domain root? This should make nest.land and more importantly other domains work without special consideration.

**Comment by lucacasonato** [comment]
> Like a sitemap file at the domain root? 

This is not scalable. deno.land/x serves more than 750.000 unique files.

Also generalizing comes at the cost of accuracy. Because we know exactly which parts of a deno.land/x url have what possible values, we can give a very specific set of options to IntelliSense. In a general list of urls (like a site map) this is not really possible anymore.

I think we can give the best user experience by supporting each registry individually for now.

**Comment by kitsonk** [comment]
Outside of re-implementing support for the registry auto completions, we won't implement a "generic" solution which crawls web servers for imports.  If a server wants to support import completions for Deno, they need to implement a `/.well-known/deno-import-intellisense.json` file which describes how their URLs are built and provide the API endpoints to provide the completion values.
