### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by promethyttrium** [denoland/vscode_deno#110]
You see new issues being opened but no progress is ever made on them some have been around for months.

**Comment by kitsonk** [comment]
No it isn't.

**Comment by David-Else** [comment]
When https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno finally stops working I don't know how I will continue to work with Deno. This extension has too many issues for me to use in its current state.

**Comment by ry** [comment]
It hasn't been abandoned - but there isn't anyone working on it now. 

I plan to dedicate some time to learning vscode extensions this week and try to get this project rolling again.

I plan to use vim to edit the extension tho :)

**Comment by mjbvz** [comment]
Hey, I work on VS Code's JS/TS support. 

Unfortunately we've had to remove this extension from the VS Code marketplace's feature extensions list because of its ongoing reliability concerns (specifically see #89) and the current state of its issue tracking. And over in VS Code's inbox, I'm having to get people to disable/uninstall this extension fairly often as it is the root cause many problems I see

Sorry to nag here and on other issue in this repo, I just am trying to make you aware of the user pain. Our crash telemetry shows about at least distinct 500 machines hit #89 at least once the past 2 weeks (this is almost certainly an underestimate since I was only looking at crashes from users on TS 3.9.6 )

Hope you can look into this soon. I can put you in contact with some TypeScript team members if you need help with the TS Service plugin related code

**Comment by kitsonk** [comment]
We have a close relationship with the TypeScript core team.  The problem here is that the main maintainer doesn't have the time to maintain it and so @ry is trying to pick up the challenge as mentioned above.  I would personally take it up, but I have limited time to dedicate to Deno at the moment and I've been buried in another thing.  We will get it sorted out for sure, but it will take a bit of time.

**Comment by David-Else** [comment]
@kitsonic @ry Why not just switch over to https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno ? That works great. Maybe @axetroy can help maintain it, maybe not, but this situation is terrible for Deno.

**Comment by axetroy** [comment]
@David-Else I have talked with @ry before. I may not have time to participate in maintenance for a long time in the future.

And I don't recommend abandoning this extension, it will lead to a split in the community.

Pin the issue the looking for maintainers maybe is a good idea.

**Comment by ry** [comment]
We are aware of the user pain. We're looking into it.

**Comment by bartlomieju** [comment]
We'll be focusing on the extension more these days. I outlined roadmap in #121.

**Comment by mjbvz** [comment]
Thank you for looking into this!
