### ISSUE TITLE
formatting does not respect "deno.config" when directory contains `deno.json`

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#1123]
**Describe the bug**

when formatting file in a directory with `deno.json`, deno_vscode ignores formatting options given in `deno.config` in settings and uses formatting setting in local `deno.json` instead.

**To Reproduce**

```
.
├── .vscode
│   └── settings.json
├── deno.json
└── src
    ├── deno.jsonc
    └── main.ts
```

`settings.json`:

```json
{
	"deno.enable": true,
	"deno.config": "./deno.jsonc",
	"[typescript]": {
		"editor.defaultFormatter": "denoland.vscode-deno"
	}
}
```

`deno.json`:

```json
{
	"fmt": { "semiColons": false }
}
```

`deno.jsonc`:

```jsonc
{}
```

save `main.ts` in vscode.

**Expected behavior**

formatting option from `deno.config` or root `deno.json` is respected (same as running `deno fmt` on project root)

**Screenshots**

https://github.com/denoland/vscode_deno/assets/54838975/8dafd138-d324-4df7-89b2-5152826bd3fb

**Versions**

vscode: 1.89.1 deno: 1.44.2+78b12a4 extension: v3.37.1

**Comment by nayeemrmn** [comment]
This is the expected behaviour now, the scope of the configured `deno.jsonc` is its parent path and `web/deno.json` will override it for files in `web/`. You can get inheritance if you use `workspace: ["./web"]` in `./deno.jsonc`. Since workspaces are experimental I recommend just copying over the fmt settings.
