### ISSUE TITLE
Explain why deno.enable exists

### ISSUE THREAD

**Issue by Tyriar** [denoland/vscode_deno#17]
The setting says:

> Controls whether deno is enabled or not.

I'm assuming this is necessary so it doesn't clash with builtin TS/node support, it would be best to spell that out though.

**Comment by axetroy** [comment]
Glad that the vscode team started paying attention to this issue

Let me explain why:

Because it is hard to distinguish between the Deno project and the general Node project

1. In general, typescript does not allow importing modules with extensions, but Deno requires

```ts
// in Node.js
import "./module"
```

```ts
// in Deno
import "./module.ts"
```

2. Deno supports importing HTTP/File protocol module

```ts
// in Deno
import "https://deno.land/std/fs/mod.ts"
import "file:///User/path/to/module/mod.ts"
```

Its module search mechanism is different with commonJS

3. Deno has default Typescript compile configuration

4. Deno does not allow import JSON module

```ts
// in Node.js. it will resolve to "./package.json"
import "./package"
```

5. and so on...

Because there are too many reasons, we cannot distinguish whether a project is a Deno project or a Node.js project.

So only use `deno.enable` as a distinguishing identifier

**Comment by justjavac** [comment]
@axetroy nice to see you again

I guess @Tyriar does not mean to explain the reason to him, but we should explain the reason to vscode users in setting

**Comment by Tyriar** [comment]
Yes I was pretty sure about the reason 🙂, but it's odd to have a toggle required in a language extension. Making more obvious by adding the reason to the setting doc would be better for users who don't know imo.

**Comment by lukepighetti** [comment]
Is the core problem that we cannot sense when we're in a Deno project as compared to a Node.js project? 

Just an idea, can we say it's a Deno project there isn't a package.json file?

**Comment by justjavac** [comment]
@lukepighetti  When `package.json` file is detected, the user will be prompted whether to disable the Deno extension. #7

We are also trying other ways https://github.com/denoland/vscode_deno/issues/39#issuecomment-629892685

**Comment by lukepighetti** [comment]
This might be worth having a different issue for what I’m about to say. What if we recommended making a library.ts file that exports all the packages you intend to use? Or deno.ts. It could solve the issue of having to copy paste urls into every file that uses a package and provide a pattern that is still pure typescript and colloquially Deno.

**Comment by maximousblk** [comment]
can we not use the differences mentioned in [issuecomment-628457462](https://github.com/denoland/vscode_deno/issues/17#issuecomment-628457462) to determine if it is a Deno project.

**Comment by promethyttrium** [comment]
As much as I've been loving working with Deno, there really should be a setting to enable Deno for a project (instead of the the reverse) because the reality is that the bulk of our projects are *not* Deno-based.

**Comment by lucacasonato** [comment]
> As much as I've been loving Deno, this really should be a setting to enable Deno for a project (instead of the the reverse) because the reality is that the bulk of our projects are not Deno-based.

This is now the case.
