### ISSUE TITLE
"A request has failed. See the output for more information" when format fails, and it always shows output as the cancel `x` button is broken

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#200]
When using the extension to format TypeScript on save,
```
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
```
it is very common that there is a problem with your code which means it can't complete. This is an advantage of format on save, it can auto-complete things for you, and it can't always be right. In the Prettier extension, there is a little logo at the screen bottom that indicates it can't format.

With the Deno extension it issues the pop-up warning:

"A request has failed. See the output for more information." 

![1](https://user-images.githubusercontent.com/12832280/92934244-28a15480-f43f-11ea-99c3-4cdaf692f26e.png)

If you press the `x` to cancel, then there is a bug as it shows the output anyway:

![2](https://user-images.githubusercontent.com/12832280/92934261-2ccd7200-f43f-11ea-9fbd-7b76953fb2cd.png)

This completely interrupts the workflow as the user now has to close two windows to continue.

**Versions**

vscode: 1.49.0
deno: 1.3.3
extension: 2.2.1

**Comment by wsmd** [comment]
I'm also having a similar issue here! Not only the output panel appears after clicking X/Cancel (which could be VSCode related bug), but also the output panel pops up automatically every time the formatter fails!

I usually keep the panel focused on the integrated terminal, and having vscode-deno takes the panel focus occasionally on formatting errors can be distracting.

I'm not sure if this is intentional, but it doesn't seems to be any error handling around the document formatting logic, which is causing those error to propagate to all the way to VSCode. 

I captured this behavior here (output appears on click X, and also the entire output panel pops up automatically on save at times)

![2020-10-05 01 18 29](https://user-images.githubusercontent.com/2100222/95043175-0ef3d580-06aa-11eb-8796-451a79e935fd.gif)

> In the Prettier extension, there is a little logo at the screen bottom that indicates it can't format.

I also like the Prettier extension's silent approach to handling formatting errors. When it fails it indicates errors using the status bar item. I went ahead and tried to implement a similar behavior here and I like it much better! To see the error, I can click the statusbar item to open the Deno Language Server output.

![2020-10-05 01 22 52](https://user-images.githubusercontent.com/2100222/95043739-aad21100-06ab-11eb-96c9-d970daafe6b0.gif)

I'm happy to open a PR if this sounds reasonable!

**Comment by axetroy** [comment]
It is not difficult to solve this issue.

The key is here:

https://github.com/denoland/vscode_deno/blob/ddfe30c5907324b623be0a9d20f1c1dc011e13fa/server/src/language/document_formatting.ts#L18-L40

This is due to `deno fmt` parsing error, throwing an exception.

We can make this async function always in Promise.resolve state so that no annoying warnings will pop up.

After an error throws, then send a notification to the client, make the client mark an error in the status bar.

**PR are welcome**

**Comment by kitsonk** [comment]
I believe this is stale and no longer applies to the v3 extension and integration with the lsp.
