### ISSUE TITLE
"deno lsp" is running even in non-deno projects.

### ISSUE THREAD

**Issue by yaegassy** [denoland/vscode_deno#346]
### Describe the bug (Description)

When I install the `vscode_deno` extension, it seems that the "deno lsp" server is always started when I open a typescript/javascript file.

Is there any way to solve this symptom other than disabling or uninstalling the extension itself?

For example, if `"deno.enable"` is `false`, can I prevent the "deno lsp" server itself from starting?

### Screenshots (DEMO)

![vscode_deno_issue](https://user-images.githubusercontent.com/188642/109106904-1b212200-7774-11eb-9667-4bdba9eb088d.gif)

### Versions

vscode: 1.53.2
deno: v1.7.5
extension: 3.0.1

**Comment by kitsonk** [comment]
The Deno LSP has to "listen" to all the information that occurs to JavaScript/TypeScript/JSX/TSX documents to be able to properly provide support for projects.  This is much the same that occurs with the built in TypeScript in VScode, the extension activates and when it sees a `tsconfig.json` or a `jsconfig.json` it starts providing additional information, it just doesn't run as a seperate process because of the nature of how it works.

**Comment by yaegassy** [comment]
Thanks for the reply. It seems to be something difficult to adjust, so I won't worry about it. 🙇
