### ISSUE TITLE
Update imports when filename changes

### ISSUE THREAD

**Issue by David-Else** [denoland/vscode_deno#410]
**Is your feature request related to a problem? Please describe.**
Using the TypeScript server when I rename a file all the imports in different files update to reflect the change. There is no need for a `.tsconfig', it just works out of the box.

**Describe the solution you'd like**
It should happen when using deno LSP.

It does not work in VS Code or Neovim LSP. I know there is a problem making it work in Neovim with the standard TypeScript server as someone has written this workaround: https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils

> - Rename file and update imports (exposed as :TSLspRenameFile)
> 
> One of my most missed features from VS Code / coc.nvim. Enter a new path (based on the current file's path) and watch the magic happen.

I hope the Deno solution will work in both editors. Neovim has deno LSP additional functions added here: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols

**Comment by scarf005** [comment]
hi, this issue was around ~2y, and i wonder if this issue could be given a higher priority. 

as OP mentioned, being able to update imports out of the box is a huge DX improvement. for example, changing location of a single file could involve updating import path for tens of files.

it'd be great to know if
1) this issue is considered for deno devteam
2) there are any hardships related to resolving this issue.

thanks in advance.

**Comment by haschu** [comment]
Hey!

This issue has been closed by [this PR](https://github.com/denoland/deno/pull/17979), which is already part of the latest release, but imports are still not updated when a filename or directory name is changed - or am I missing something?

**Comment by yacinehmito** [comment]
@dsherret I am wondering the same as @haschu. How can we benefit from this?

**Comment by bartlomieju** [comment]
This appears to be the same issue as https://github.com/denoland/vscode_deno/issues/692
