### ISSUE TITLE
Deno appears in the status bar regardless of whether workspace has "deno.enable": true

### ISSUE THREAD

**Issue by dsherret** [denoland/vscode_deno#459]
I don't see any code that prevents this as right now the commands are registered and then it runs the code to start the language server.

We should register the commands, but only start the language server when the extension is enabled. If someone runs the "Deno: Restart Language Server" command and `"deno.enable"` is not true, then we should tell them to run "Deno: Initialize Workspace".

I checked my global configuration and `"deno.enable"` was not `true`.

![image](https://user-images.githubusercontent.com/1609021/123516696-718f6600-d66b-11eb-97cf-2dc015283893.png)

**Comment by lucacasonato** [comment]
@dsherret The reason we do this is to make the formatteer work even if Deno is not enabled in a workspace (allow the builtin "Deno Formatter" to work in a Node project).

**Comment by dsherret** [comment]
@lucacasonato oh, interesting. I don't have it configured to be used as a formatter though. Perhaps it should only start the language service if it is? Also, perhaps it should be lazily initialized for when a format occurs or instead of starting a background process for formatting it could use stdin and the `deno fmt` command when `"deno:enabled"` is not `true`?

**Comment by lucacasonato** [comment]
@dsherret The extension (and with it the LSP) should only start if you do one of the following right now:

- open a JS, TS, JSON, or MD file
- run a `Deno:` command from the command palette
- start the debugger with Deno configured

I guess what you want to do is only start the LSP in the extension if `deno.enable` is in any configs / commands are triggered, and alternatively fall back to formatting via stdin? I would rather go and profile the LSP and make it more lightwheight for the scenario where `deno.enable` is not set (for example don't start TSC).

**Comment by dsherret** [comment]
I just find it weird that I'm working on something unrelated to Deno, don't have formatting enabled to use Deno, and don't have `"deno.enable": true` in the repo and yet I see it running in the bottom right corner. I'd rather it not start at all in this scenario. Thinking about it more, I guess yeah if someone is using it for formatting then it's annoying to have two ways of doing something. I think in that case to simplify things then we should start it, but not in my case here where it has no use.

**Comment by kitsonk** [comment]
Just like the built in TypeScript plugin runs even if Deno is enabled, there is also state that needs to be tracked so that if someone does enable it, it doesn't require a restart. It gets a lot more complicated with workspace folders where Deno can be disabled and enabled.

I think the only actionable aspect would be to not display the status info on non-Deno enabled projects or on projects where at least one workspace folder is enabled.

Not displaying it if people are only using it as a formatter doesn't feel like it will be missed.

**Comment by KevinBatdorf** [comment]
Came here from Google. I started using Deno for a small side project and now it's giving me irrelevant code hints in my React app. Posting here since I'm not sure how to disable it without just disabling the extension until I need it.

Any ideas? Thanks

![Screen Shot 2021-07-15 at 7 04 37 PM](https://user-images.githubusercontent.com/1478421/125868627-32563184-d601-40c6-a877-a57c70633955.png)
(unrelated, but a nice side effect is it identified a bug my linter config missed)

**Comment by kitsonk** [comment]
@KevinBatdorf is that vscode? If it is, it is likely you enabled Deno globally. It only should supply diagnostics when `deno.enable` is `true`.

**Comment by KevinBatdorf** [comment]
Yeah, you're right. Unchecking this option did make the errors go away. I should have also checked the config for `deno.enable` as mentioned above.

![Screen Shot 2021-07-15 at 8 03 47 PM](https://user-images.githubusercontent.com/1478421/125872625-7eb46d06-c30a-4804-b818-5621011d5de5.png)

I remember reading the warning actually, and not connecting the two, or maybe I thought globally for all Deno projects 😫 ? Thanks for the quick reply!

**Comment by kitsonk** [comment]
Yeah, the challenge is that there is no great way to "detect" a Deno project. It would be guessing. We are working on a optional unified meta data file, and that would allow us to "magically" enable Deno for a project without having to do it explicitly.

**Comment by dsherret** [comment]
I'm going to close this now that #485 landed.

**Comment by tylerbutler** [comment]
I installed the extension, and even when `deno.enable` is false in both my personal settings _and_ the workspace settings, if I open a TypeScript file, I get error popups if Deno isn't installed:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/19589/174913298-951d5c4d-3207-432f-88ed-098a277b4e2d.png">

This happens to me a lot because I use Codespaces and devcontainers all the time, and they don't have Deno installed unless they're, you know, using Deno. As it stands, I don't see how I can even leave the extension enabled. I have to manually enable and disable the extension -- not a setting of the extension, the whole thing -- whenever I want to use it on a project.

Is this the expected experience? If I enable the extension and Deno isn't on the path I get an error on every TypeScript file I open? And the only workaround is to not use the extension?

**Comment by dsherret** [comment]
@tylerbutler no, that’s not a good experience and should be fixed. This issue is related, but not the same. Would you be able to open an issue? (Sorry, I’m not at my computer right now and just quickly messaging)

**Comment by tylerbutler** [comment]
@dsherret I'm happy to open a separate issue. I'll do that tomorrow.
