### ISSUE TITLE
Support the new Testing API in VSCode 1.59+

### ISSUE THREAD

**Issue by johnspurlock** [denoland/vscode_deno#487]
The VSCode extension api for testing is now out of preview and part of the current shipping release (1.59, released Aug 6).

It would be great for the deno extension to support the new testing extension apis (see `createTestController` in the new `tests` namespace), it would seem to line up well with the functionality of `deno test`

https://code.visualstudio.com/updates/v1_59#_testing-apis

**Comment by kitsonk** [comment]
I've taken a look at this and it is a non-trivial, but certainly desired.

Here is the extension guide: https://code.visualstudio.com/api/extension-guides/testing.  It would require some custom APIs with the language server to identify the tests.  We currently have the logic to generate the code lenses for the test, so that should be straight forward enough.  Also, there should be integration to run the tests, and that will be more complicated as I don't believe we want to run it as a sub process like we do with the code lens tests, we would in fact want to run the test directly in the language server so that we can conform the data and supply it back as a result to feed the IDE.  This complicates things significantly.

**Comment by Igorgro** [comment]
FYI: the same feature has recently been added to vscode-jest extension: https://github.com/jest-community/vscode-jest/pull/742

**Comment by johnspurlock** [comment]
Thank you!
