### ISSUE TITLE
Top-level 'await' is not recognized by extension

### ISSUE THREAD

**Issue by rjkz808** [denoland/vscode_deno#49]
I have installed latest [Deno extenstion](https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno) version from VSCode marketplace and everything is ok except the top-level `await` statements. It seems that extension just does not recognize them:

![image](https://user-images.githubusercontent.com/38258624/82445923-5b00fd80-9aae-11ea-9634-2f459fb2eaf9.png)

Output of `deno --version` command:

```bash
❯ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

VSCode version:

```bash
❯ code --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
```

OS: macOS Mojave 10.14.6 18G2022 x86_6

**Comment by rjkz808** [comment]
Hm, maybe this issue only occurs in `v1.42.1` vscode because I've tried Deno extension in `v1.45.1` one and it works fine. `README.md` of this project says that it supports `VS Code 1.40+ and TS 3.8+`. But it doesn't really work in 1.42.1, so I think this problem should be mentioned

**Comment by gewoonwoutje** [comment]
Typescript only recently added top-level await support. The typescript version is shipped with VS Code, which is updated when you update VS Code. I think the problem was the used typescript version (in VS Code, which may be different than your deno typescript version, or npm/yarn globally installed typescript version) was older in your previous 1.42.1 setup.

That said, it would be great if the plugin would enable selecting the deno typescript version in VS Code.
![image](https://user-images.githubusercontent.com/9407072/82708239-09a76880-9c7e-11ea-8451-ff59d6d83685.png)

**Comment by detj** [comment]
I'm seeing `ts1378` instead of `ts1308`. Not sure if what I'm getting is directly related to this issue or not.

```
Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.ts(1378)
```

Here are the steps I followed:

1. Installed the extension
2. Created `.vscode/settings.json` with following entry

```json
{
  "deno.enable": true,
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  }
}
```

3. Wrote a basic [oak](https://oakserver.github.io/oak/) server

```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  console.log("received request", ctx.request);
  ctx.response.body = "Hello World!";
});

console.log("oak server listening at http://localhost:8000");

await app.listen("127.0.0.1:8000"); // ts1378 triggering on this line
```

![image](https://user-images.githubusercontent.com/280236/90340773-328a9000-e018-11ea-81ba-412878da2a7b.png)

Here are the version details:

```sh
$ deno --version
deno 1.3.0
v8 8.6.334
typescript 3.9.7
```

VSCode is also using TypeScript v3.9.7

**Comment by lucacasonato** [comment]
Make sure your `.vscode` folder is in the folder that you have opened in VS Code, not in a child of that folder.

**Comment by lucacasonato** [comment]
Should be resolved in version 3.x of the extension.
