### ISSUE TITLE
Enable extension when a config file is auto-discovered by language server

### ISSUE THREAD

**Issue by ije** [denoland/vscode_deno#617]
Since deno 1.18+ will automatically discover configuration files with the `deno.json` or `deno.jsonc` filenames, i think we should enable extension automatically by  finding`deno.json` or `deno.jsonc`, instead of enable it in `.vscode/settings.json`

**Comment by kitsonk** [comment]
This was the idea behind introducing it.

That being said, my thinking is we want to wait at least until 1.19 to introduce it and it isn't as straight forward as it would seem though, as it requires enablement in both the LSP and the client, because currently enablement is totally driven by the client and with vscode_deno requires "muting" the built in TypeScript diagnostics.  So this would require the language server to notify the client that a config file has been auto identified.

There is also the semantics of what happens when `"deno.enable"` is explicitly set to `false` or `true`.

**Comment by kitsonk** [comment]
When a config file is discovered, the user will be prompted to enable the workspace.
