### ISSUE TITLE
`deno.enablePaths` conflict with build in typescript language server.  

### ISSUE THREAD

**Issue by nurmohammed840** [denoland/vscode_deno#668]
In other word, `deno.enablePaths` doesn't disable default typescript language server from running specified path.

So both `deno` and `typescript` language server running on the same project...
  
 
**Versions**

```
deno 1.22.0 (release, x86_64-pc-windows-msvc)
v8 10.0.139.17
typescript 4.6.2
```

Vscode version:

```
Version: 1.67.2 (user setup)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by ragrag** [comment]
@nurmohammed840 any updates or workarounds u have with this problem?

**Comment by kitsonk** [comment]
Can you provide the output of _Deno: Language Server Status_ from the command pallet in vscode for the workspace you have that you are concerned about.

When you say:

> So both deno and typescript language server running on the same project...

What do you mean specifically.  The whole purpose of `deno.enablePaths` is to have the two co-exist together in the same workspace.

**Comment by ragrag** [comment]
Hello @kitsonk thank you for the follow up.
Currently I have this configuration that is working as expected on macOs 12.1 but not on Windows 10

Current directory structure:
  .vscode/settings.json
  scripts
  services

I want Deno Language Server to only work for the ```scripts``` directory and ignore services (which has node ts projects).
the current configuration I have in settings.json is
```json
{
    "deno.lint": true,
    "deno.unstable": true,
    "deno.enablePaths": ["./scripts"]
}
```
This current configuration works perfectly on macOs.

As for windows 10:
- Files in ```scripts``` directory are still not detected by the Deno Language Server while files in ```services``` are picked up by the built-in Typescript Language Server. im assuming after many trials that ```deno.enablePaths``` effectively doesn't do anything in this case
- After adding  ```"deno.enable" : true``` (which according to the docs should be ignored if ```deno.enablePaths``` is provided) the files in ```scripts``` are picked up by the Deno Language Server and the files in ```services``` are ignored. however they are not picked by the Typescript Language Server either (no errors but also noIntellisense). when I remove ```deno.enablePaths``` at this point they start to show errors since the Deno Language Server is not ignoring them anymore.

I hope that was not confustion, i will also be willing to do some screen recordings if that is necessary

**Comment by nurmohammed840** [comment]
![Screenshot](https://user-images.githubusercontent.com/46383294/172108189-6cab8209-cadc-43b9-9933-d2c624090393.png)

_Deno: Language Server Status_

```json
{
  "enable": false,
  "enablePaths": [
    "./server"
  ],
  "cache": null,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": false
  },
  "internalDebug": false,
  "lint": false,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://crux.land": true,
        "https://deno.land": true,
        "https://x.nest.land": true
      }
    }
  },
  "testing": {
    "args": [
      "--allow-all",
      "--no-check"
    ],
    "enable": true
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": false
}
```

**Comment by WudsyWudsyWudsy** [comment]
I have a similar issue to @ragrag on Windows 11 (and 10).

## Set up

Current `settings.json`:
```
{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": false,
    "deno.enablePaths": [
        "./deno"
    ]
}
```

Folder structure:
```
test_project/
├─ .vscode/
│  ├─ settings.json
├─ deno/
│  ├─ deno_main.ts
├─ typescript/
   ├─ typescript_main.ts
```

## Expected behavior
 
My understanding is that this set up _should_ yield the following result:

`deno_main.ts`:

- deno language server enabled
- typescript language server disabled


`typescript_main.ts`:

- deno language server disabled
- typescript language server enabled

## Observed outcome

What I am _actually_ getting is:

`deno_main.ts`:

- deno language server enabled
- typescript language server disabled


`typescript_main.ts`:

- deno language server disabled
- typescript language server **disabled** <--- Unexpected

In this case (where `"deno.enable"` is `true`) typescript language server is disabled on `typescript_main.ts`, despite me wanted it to be active.


If I change `"deno.enable"` to `false` I get the follow:

`deno_main.ts`:

- deno language server enabled
- typescript language server **enabled**  <--- Unexpected


`typescript_main.ts`:

- deno language server disabled
- typescript language server enabled


In this case (where `"deno.enable"` is `false`) both deno and typescript language servers are active on `deno_main.ts`, which causes conflicts.

## Issue

It appears to me that the following is happening (on Windows 10 and 11):
1) `"deno.enablePaths"` is correctly controlling what files and folders the deno language server is active on, however;
2) `"deno.enable"` is **not** being ignored
    - if it is `true`, the typescript language server is disabled on **all** files in the project, regardless of if they are in the `enabledPaths` or not
    - if it is `false`, the typescript language server is enabled on **all** files in the project, regardless of if they are in the `enabledPaths` or not

## Desired outcome

Desired outcome would be as follows:
- "deno.enable"` is ignored
- files and folder which deno language server runs on is unchanged (those in `"deno.enablePaths"`)
- files and folder which are **included** `"deno.enablePaths"` should have typescript language server **disabled**
- files and folder which are **not included** `"deno.enablePaths"` should have typescript language server **enabled**

**Comment by alexndremelyanov** [comment]
I had a similar issue. My decision was to disable `typescript.tsserver.experimental.enableProjectDiagnostics`

**Comment by WudsyWudsyWudsy** [comment]
> I had a similar issue. My problem was solved by disabling `typescript.tsserver.experimental.enableProjectDiagnostics`

@alexndremelyanov can you please explain your issue? What was similar and what was not?

This setting was disabled by default for me, enabling it (or re-disabling it) didn't change any of my results from above.

**Comment by lts20050703** [comment]
Can confirm.
`deno.enablePaths: ["./worker"]` and `deno.enable: false` does not disable typescript lsp **inside** `"./worker"`
`deno.enablePaths: ["./worker"]` and `deno.enable: true` does not disable deno lsp **outside** of `./worker`

**Comment by jigz** [comment]
having the same issue on my monorepo

**Comment by WudsyWudsyWudsy** [comment]
I was having a play around to see if I could identify the issue. I found the following in my Extension Host Log:
```
[2022-07-05 20:05:42.551] [exthost] [warning] [denoland.vscode-deno] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'deno.enable', provide the URI of a resource or 'null' for any resource.
[2022-07-05 20:05:42.551] [exthost] [warning] [denoland.vscode-deno] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'deno.enablePaths', provide the URI of a resource or 'null' for any resource.
```

Not sure if these could be related.

**Comment by jeiea** [comment]
I felt LSP has poor support for windows..

**Comment by alexishecf** [comment]
Any update on this? I have the problem in my monorepo as well:  TypeScript language server runs for files provided in enablePaths but not the Deno language server. It works as expected if I use `enable`  and  get rid of `enablePaths`.

deno 1.27.0 (release, x86_64-pc-windows-msvc)
v8 10.8.168.4
typescript 4.8.3
```

.vscode/settings.json
```
{
  "deno.unstable": true,
  "deno.enablePaths": ["./backend-deno"],
  "deno.importMap": "./backend-deno/import_map.json"
}
```

**Comment by drocha87** [comment]
I'm also having problem with `deno.enablePaths`

Here is the output of the deno extension
```txt
Starting Deno language server...
  version: 1.27.0 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\diego\.local\bin\deno.exe
Connected to "Visual Studio Code" 1.72.2
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Server ready.
successfully cancelled request with ID: 1
Unable to send result to client.
client asked to cancel request 2, but no such pending request exists, ignoring
```

My `.vscode/settings.json`
```json
{
  "deno.lint": true,
  "deno.unstable": true,
  "deno.enablePaths": ["./supabase"]
}
```

And my `Deno: language server status`
```json
{
  "enable": false,
  "enablePaths": [
    "./supabase"
  ],
  "cache": null,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": false
  },
  "inlayHints": {
    "parameterNames": {
      "enabled": "none",
      "suppressWhenArgumentMatchesName": true
    },
    "parameterTypes": {
      "enabled": false
    },
    "variableTypes": {
      "enabled": false,
      "suppressWhenArgumentMatchesName": true
    },
    "propertyDeclarationTypes": {
      "enabled": false
    },
    "functionLikeReturnTypes": {
      "enabled": false
    },
    "enumMemberValues": {
      "enabled": false
    }
  },
  "internalDebug": false,
  "lint": true,
  "suggest": {
    "completeFunctionCalls": false,
    "names": true,
    "paths": true,
    "autoImports": true,
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://deno.land": true,
        "https://x.nest.land": true,
        "https://crux.land": true
      }
    }
  },
  "testing": {
    "args": [
      "--allow-all",
      "--no-check"
    ],
    "enable": true
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": true
}
```

I'm working now with my project with `wsl` and it works perfectly, I would like just to add that in windows it's not working properly, so the workaround is to use `wsl` if it's even possible in your case.

**Comment by joshdoesthis** [comment]
The following workspace _settings.json_ has worked for me. Adding an import map was what was needed to tie it all together.
```
{
  "deno.enable": true,
  "deno.enablePaths": ["./src"],
  "deno.importMap": "./deno.json",
  "deno.lint": true
}
```
