### ISSUE TITLE
"deno.cache" in global settings causes creation of deno-dir even if deno.enable is false

### ISSUE THREAD

**Issue by qgates** [denoland/vscode_deno#674]
In global settings, if we have
```
   "deno.cache": ".\\deno-dir"
```
a `deno-dir` is created in every project folder opened by vscode with a whole bunch of vscode related deno stuff, _even if `deno.enable` is false_

Moving `deno.cache` to workspace settings fixes and is a workaround, but the behaviour seems incorrect: vscode_deno shouldn't pollute non-deno projects and should only activate when `deno.enable` is true (typically in workspace settings)

**Versions**

vscode: 1.67.2 deno: 1.22.2 extension: 3.12.0

**Comment by kitsonk** [comment]
This is a design limitation, because even though `"deno.enable": false` is set, the Deno language server is still started to provide formatting capabilities if configured as well as to be able to be enabled without requiring a restart.  Because the process is started, the `deno` executable will still track changes to files and be prepared to start issuing diagnostics if required.

**Comment by nayeemrmn** [comment]
We no longer start the language server if `"deno.enable": false`. Though, related: https://github.com/denoland/vscode_deno/issues/1119#issuecomment-2179239834.
