### ISSUE TITLE
File changes are not debounced to the language server.

### ISSUE THREAD

**Issue by Industrial** [denoland/vscode_deno#689]
**Describe the bug**
Flashing errors / hanging language server for 30 seconds.

**To Reproduce**
Currently when I edit documents that contain a lot of types/backend like React components with MaterialUI for example it happens that when I am making edits quickly it will flash errors for 30 seconds. It looks like all changes are pushed into a queue and sent into the language server and then processed one by one.

**Expected behavior**
When updating the language server with information from the document, cancel and throw away all request but the last one. This will ensure only the version of the document that you care about (when you stop typing) will be checked for errors.

VSCode: 1.67.2
VSCode Deno: [3.13.0](https://github.com/denoland/vscode_deno/compare/3.12.0...3.13.0)

**Comment by kitsonk** [comment]
This is more complex than it sounds.  That changes are applied as quickly as they are received.  The diagnostic calculation is debounced already.  The TypeScript language server is single threaded and things like completions and other requests take a higher priority than a diagnostic run.  Once those requests have been completed and there isn't further input coming in. A diagnostic run is requested.  This enables the language server to be more responsive, but if there are other requests sent and are in the language server, they can't be cancelled, because of the non-async nature of the async server for many requests.

The changes cannot be discarded, because they are cumulative.

We still have some work to do with dealing with fully supporting cancellation tokens throughout the whole stack, which will help in some cases, but it is complicated. @dsherret has been looking at it.

What version of Deno are you using?

**Comment by Industrial** [comment]
This was on 1.23.0.

**Comment by bartlomieju** [comment]
I believe this is now fixed and we do debounce inside LSP. Feel free to reopen if the problem persists.
