### ISSUE TITLE
Set root folder for plugin

### ISSUE THREAD

**Issue by parliament718** [denoland/vscode_deno#75]
Is there a away to set the root folder for the deno code? Currently it seems like it can only be limited to a workspace but my workspace contains the following:

workspace
   |--client (Angular app)
   |--server (deno app)

Enabling the plugin globally or for the workspace results in me geting all sorts of errors in my Angular project (bad imports without extensions). 

Multiple workspaces in a single window is not yet a feature in vscode so I have to use multiple vscode windows. 

Is there a way to avoid this?

**Comment by garysb** [comment]
This is extremely annoying for me. We too have multiple angular clients and then have multiple lambda functions on the server, some written in typescript, some in javascript, and now some in typescript with Deno.

What would be helpful is if we could have the Deno extension only be enabled for the parts that are actually Deno without having to disable the extension on every project that is NOT Deno. So basically, globally disabled by default and explicitly enabled for a directory within my workspace.

**Comment by Ciantic** [comment]
Even if deno never had a configuration file (because getting rid of package.json was one of the goals), I could see a dummy file for IDE support being useful.

If some dir had a file like `.denoproject` then the IDE  could deduce it needs to enable Deno's typescript plugin for files inside that directory:

`somedir/.denoproject`
`otherdir/yournode app`

I also find it a bit annoying that Deno plugin is enabled by default, of course I disabled it by default because most projects at the moment are not Deno projects. However if there was a dummy file that wouldn't be a problem, because the extension could be made to trigger when it sees that file.

**Comment by Flaque** [comment]
See #92

**Comment by CGQAQ** [comment]
#194 included

**Comment by lucacasonato** [comment]
Closing in favor of https://github.com/denoland/vscode_deno/issues/314
