### ISSUE TITLE
feat: include and exclude options for InlayHints

### ISSUE THREAD

**Issue by thomas3577** [denoland/vscode_deno#782]
In my projects I often have an assets folder which also contains JavaScript files for the web client.
In these files the InlayHints are rather annoying.

Would it be possible to provide the option "include" and "exclude" like for fmt and lint?

**Comment by jiawei397** [comment]
I also need this function. `Deno.enablePaths` doesn't seem to satisfy me.

I need an exclusion path array because the whole project is **Deno**, but a folder does not need to be verified with it. Although I can use `Deno.enablePaths` to include my folders, it cannot contain the root directory, so it cannot solve this problem.

I noticed that `deno.json` now supports the `exclude` and `include` of `lint` and `fmt`. It would be better if could read its configuration directly.
```json
 "lint": {
    "files": {
      "exclude": ["static/", "views/"]
    }
  },
```

**Comment by nayeemrmn** [comment]
Seems solved by `deno.disablePaths`.
