### ISSUE TITLE
Even if I select "lint:Yes" in "Deno: initializeWorkspace", lint is not enabled.

### ISSUE THREAD

**Issue by ayame113** [denoland/vscode_deno#786]
After #665, the "deno.lint" setting should be true by default, but it doesn't seem to be the case.

**Comment by Leokuma** [comment]
**To Reproduce**

1. Disable Deno Lint under Settings
2. Initialize a workspace (command `Deno: Initialize Workspace Configuration`)
3. Answer "Yes" when asked about enabling Deno linting

**Expected behavior**
Setting `"lint": true` should be persisted to the current workspace.

**Actual behavior**
No lint setting is persisted, effectively ignoring the previous user's answer.

The same problem occurs for the "Unstable" setting.

**Comment by ayame113** [comment]
postscript:
When I checked again, I found that the direct cause was that `lint: false` was set in the global setting.
However, if the user selects `Enable deno linting: Yes`, I think we should respect that choice and write `lint: true` in user's workspace settings regardless of what your global settings are.
(So fix #799 looks good to me.)

**Comment by topperspal** [comment]
may be deno lint is enabled by default because when we chose enable lint to No, it set deno.lint: false

**Comment by bartlomieju** [comment]
Sorry for a slow response folks. Do you experience the same issue when using latest extension and Deno versions?

**Comment by Leokuma** [comment]
@bartlomieju Yes, it still happens in the latest VSCode (1.80.0) and latest Deno (1.35.0). I just tested.

I opened this fix: #799

**Comment by bartlomieju** [comment]
Thanks @Leokuma, we will prioritize reviewing your PR.
