### ISSUE TITLE
Inlay hints are super aggressive, I would like one easy setting to completely disable them

### ISSUE THREAD

**Issue by justinmchase** [denoland/vscode_deno#788]
**Is your feature request related to a problem? Please describe.**

I just got an update and am suddenly barely able to read my code, maybe others find them useful but for me, its just adding a ton of visual noise. For example, if I wanted to see the return type of a function all the time, then I'd explicitly add it. I like the implicit return because it reduces the visual noise, so to have it suddenly show up again is just counter to how expect it to be.

So I then went into the settings to turn it off and found I had to disable 7 checkboxes and flip one drop down to completely disable it. 

By default I'd like to see _as little as possible_ then being able to use my mouse hover to get more details and drill in with cmd+click, this is ideal. Showing _more_ all the time is not desirable for me at all. 

**Describe the solution you'd like**

Personally, I'd like the setting off entirely by default, but at the very least a single enable/disable checkbox which, when unchecked would completely disable the behavior regardless of the other settings.

**Comment by Leokuma** [comment]
Related https://github.com/denoland/vscode_deno/issues/744

**Comment by lukeed** [comment]
100% this – they're extremely distracting and it took me a while to figure out how to turn them all off.

Not only should there be a global "turn these off" button, but this feature should be respecting VSCode's `"editor.codeLens": false` global setting.

**Comment by lukeed** [comment]
The `deno.codeLens.*` flags should also respect `"editor.codeLens"` too FWIW. I'm not sure why this extension tries to separate "inlayHints" vs "codeLens" – it all falls under "codeLens" everywhere else

**Comment by bartlomieju** [comment]
> 100% this – they're extremely distracting and it took me a while to figure out how to turn them all off.
> 
> Not only should there be a global "turn these off" button, but this feature should be respecting VSCode's `"editor.codeLens": false` global setting.
> 
> edit: found `"editor.inlayHints.enabled"` in linked issue

This seems reasonable to respect `editor.codeLens`.

@crowlKats please take a look when you find time

**Comment by KnorpelSenf** [comment]
I would go even further and disable them by default.

It's not just that they can also make the code very hard to read: especially people with little coding experience are often confused by them. This feature effectively makes it harder to get started with Deno (source: I am maintaining a lib that often attracts newcomers and one of the first things everyone asks is how to turn off "the mess").

In #744 it was said that the majority likes inlay hints. In my personal experience, that's not the case. (What's this data based on?)

In addition, I find it very reasonable to disable distracting features by default, and then letting experienced users opt in—rather than shying away those who are just getting started.

**Comment by bartlomieju** [comment]
Given lots of reactions we are inclined to disable the inlay hints by default. I will take a look if we need to cut another Deno release to do that, or can it be handled on the extension side only.
