### ISSUE TITLE
cannot ignore specific file for linting

### ISSUE THREAD

**Issue by scarf005** [denoland/vscode_deno#791]
**Describe the bug**
due to github workflow using npm based script, I'm stuck with `.cjs` files with `jsdoc`. however, I am unable to ignore it from being linted and it gives me errors.

```
**To Reproduce**
```cjs
// commitlint.rules.cjs 

// deno-lint-ignore-file
/* eslint-disable no-undef */
//@ts-check
/** @typedef {import('@commitlint/types').UserConfig} UserConfig */
```
running deno won't give errors.
```json
deno lint .github/commitlint.rules.cjs --json
{
  "diagnostics": [],
  "errors": []
}
```

however, deno extension will give out the following error:
```
Relative import path "@commitlint/types" not prefixed with / or ./ or ../deno(import-prefix-missing)
```

**Expected behavior**

be able to ignore specific file/line for linting

**Screenshots**

![image](https://user-images.githubusercontent.com/54838975/212679796-575be5cd-bcc3-4211-b090-ca4ed6ef680c.png)

**Versions**

vscode: 1.74.3 deno:  1.29.3 extension: 3.16.0

**Comment by bartlomieju** [comment]
@scarf005 the error you are getting is from Deno's TypeScript server, not linter and that's why `deno-lint-ignore-file` directive has no effect here.

Do I understand it right that this file is part of your workspace, but you don't want Deno to lint and type check it? If so maybe `deno.enablePaths` setting would solve the issue here?

**Comment by scarf005** [comment]
yes, closing in favor of #817 and #834
