### ISSUE TITLE
Plugin does not respect user tab settings

### ISSUE THREAD

**Issue by xXACCEXx** [denoland/vscode_deno#81]
Not to start a tabbing war, but I have explicitly set these settings, and they are ignored when formatting.

```
{
  "editor.insertSpaces": false,
  "editor.tabSize": 4
}
```

**Comment by xXACCEXx** [comment]
It seems to be overriding `"editor.formatOnSave": true,` as well, even though according to the deno docs, the `deno.autoFmtOnSave` is false by default and has not been implemented...

**Comment by xXACCEXx** [comment]
Also, for ticket completeness, I have uninstalled all vscode plugins, and its fine, install https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno or https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno and problem occurs.

**Comment by TTSKarlsson** [comment]
I can confirm this. No matter what formatter used and what tab spaces, it always formats the same way using the format document shortcut.

**Comment by jsejcksn** [comment]
I decided to dig into this just now. You have control over which formatter is used for different filetypes in VS Code. There is information about how to customize this behavior and other language-specific behaviors at the [VS Code docs > Get Started > Settings > Language specific editor settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings).

When editing your `settings.json` file, intellisense will help you find the valid keys and values, but these are likely the settings that you want:

```json
{
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
}
```

If you use those settings, VS Code will use the built-in formatter instead of the one provided by the Deno extension, when editing `.js`, `.jsx`, `.ts`, `.tsx` files.

If you are uncomfortable editing your `settings.json` file, you can use the command palette to change the default formatter while editing a document of that type. Here is an example while I was editing a TypeScript document:

![vscode-default-formatter](https://user-images.githubusercontent.com/868251/84526478-fa2aa680-aca2-11ea-9de7-7dfb569240ad.gif)

**Comment by xXACCEXx** [comment]
Marvellous, Thank you for these suggestions and the link to the docs. They are super informative.

I've fixed my issues using the default formatter value `vscode.typescript-language-features` like you suggested, but only for javascript and typescript.

**Comment by lucacasonato** [comment]
The extension does not have auto format on save anymore now. The tab size is determined by `deno fmt` for the deno formatter, and is not configurable. As for not enabling the extension by default, I agree: see #193.
