### ISSUE TITLE
A way to disable deno for JavaScript

### ISSUE THREAD

**Issue by Mqxx** [denoland/vscode_deno#871]
**Is your feature request related to a problem? Please describe.**

Unfortunately, it is currently only possible to activate Deno globally in the entire project. For example, if I am working on a project where I have both a client and a server, I would like to have Deno enabled only for my TypeScript backend. If Deno is also enabled for JavaScript then I have no access to for example the DOM or other "frontend only" APIs. Then when I want to work on my client, I get autocomplete only when I disable Deno.

**Describe the solution you'd like**

I would wish that you could turn Deno on/off specifically for certain languages. As an example like this:

```json
{
    "deno.enable": true,
    "deno.unstable": true,
    "[javascript]": {
        "deno.enable": false <-- Grayed out (does not work)
    }
}
```

**Comment by markthree** [comment]
Maybe you can do this 👇
```jsonc
{
  "deno.enable": true,
  "deno.unstable": true,
 "deno.enablePaths": ["./your/serviceDir"]
}
```

**Comment by Mqxx** [comment]
That works thanks for the suggestion!
But I would still like to be able to disable Deno for certain languages.

**Comment by nayeemrmn** [comment]
It's more reasonable for the use case described to allowlist by directory, per-language doesn't make a lot of sense. Declining for now.

**Comment by jsejcksn** [comment]
> Declining for now.

@nayeemrmn Will you re-open and close this again as [`not planned`](https://github.com/denoland/vscode_deno/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) (instead of [`completed`](https://github.com/denoland/vscode_deno/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted)) so that it can be [correctly indexed](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/)?
