### ISSUE TITLE
Inconsistent behaviour when using triple-slash directives

### ISSUE THREAD

**Issue by smitssjors** [denoland/vscode_deno#872]
**Describe the bug**
Fresh projects include the following triple-slash directives in the `main.ts` file.
```ts
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />
```
Now sometimes using unstable APIs does not give an error in the editor but sometimes it does, for example in the SaaSKit project (see https://github.com/denoland/saaskit/pull/279). Setting `"deno.unstable": true` does not have any effect.

**To Reproduce**

I have no idea how to reproduce this. After creating a new clone of the SaaSKit project the error went away but I am not sure why since it was of the same version.

**Expected behavior**

I expect that using unstable APIs would result in a error, unless explicitly enabled.

**Screenshots**

<img width="998" alt="image" src="https://github.com/denoland/vscode_deno/assets/18398194/43c13798-d973-4630-ae8f-7148e55b4376">

Error message: `Property 'openKv' does not exist on type 'typeof Deno'. Did you mean 'open'?`

**Versions**

vscode: 1.79.2 deno: 1.34.3 extension: 3.19.1

**Comment by zwn** [comment]
I have set the extension config

```json
"deno.unstable": true
```

but `Deno.openKv()` is not recognized.

![image](https://github.com/denoland/vscode_deno/assets/1130051/35e9a59b-4654-4a3c-8aa3-69d886c8a3ba)

If I add 

```ts
/// <reference lib="deno.unstable" />
```

It is recognized. 

![image](https://github.com/denoland/vscode_deno/assets/1130051/84da75dd-4e0c-46a0-b9c5-d49634126068)

I was under the impression that setting `deno.unstable` to `true` should be enough. What is the expected behavior here?

- vscodium 1.80.0
- deno 1.35.1
- extension v3.19.1

**Comment by bartlomieju** [comment]
@dsherret do you consider this fixed with https://github.com/denoland/deno/pull/19825?

**Comment by nayeemrmn** [comment]
This is caused by https://github.com/denoland/deno/issues/9541 I assume.

**Comment by nayeemrmn** [comment]
We no longer have separate type checking for unstable.
