### ISSUE TITLE
esm.sh types are not picked up

### ISSUE THREAD

**Issue by rgripper** [denoland/vscode_deno#875]
**Describe the bug**
When generating a new Fresh 1.2.0 project, JSX and any library imported from `esm.sh` do not have types loaded, while the tooltip shows the correct types url following which types can be downloaded and work locally if copied. 
`npm:`  and denoland-based packages are working fine.

![image](https://github.com/denoland/vscode_deno/assets/129794/8cd24864-aa30-492d-9cbd-b419457fb874)

**To Reproduce**

1. Create a new Fresh 1.2.0 project using the [getting-started](https://fresh.deno.dev/docs/getting-started/create-a-project) page
```sh
deno run -A -r https://fresh.deno.dev
cd fresh-project
deno task start
```
2. open in VSCode
3. hover over imports syntax: esm.sh-based imports provide no autocompletion and tooltip on the used types does not contain any signatures

**Expected behavior**

When I use imports, autocompletion works and tooltips show signatures

![image](https://github.com/denoland/vscode_deno/assets/129794/8c952468-6e8a-4ab6-98f8-fff9022132d0)

**Screenshots**

![image](https://github.com/denoland/vscode_deno/assets/129794/0f675b7d-4244-41da-9695-0ca589d62f04)

**Versions**

vscode: 1.79.2 deno: 1.34.3 extension: 3.19.1

**Comment by mazniak** [comment]
I am experiencing this same issue independent of Fresh. Just set up an empty directory, run `deno init` and change the main.ts to something like (after running `npm i stripe`)
```ts
import Stripe from "npm:stripe";

import Stripe2 from "https://esm.sh/stripe@12.12.0";

type t = Stripe.Price['id']
type u = Stripe2.Price['id']
```
The npm import has correct type info eg
![a](https://github.com/denoland/vscode_deno/assets/103123/f5020707-96a5-4426-a8a3-1e68362f445e)

While the esm.sh import is nonsense

![b](https://github.com/denoland/vscode_deno/assets/103123/7acc71e8-5541-4b88-9d3b-2068ee6495a3)

I see nothing in the error or server logs to indicate an issue or error. 

Some esm.sh imports _do_ work:

```ts
import merge from "https://esm.sh/ts-deepmerge@5.0.0";
```

![c](https://github.com/denoland/vscode_deno/assets/103123/56326690-58f3-4d93-99fc-227cb084130c)


I have no idea why though

**Comment by deckchairlabs** [comment]
Yeah this makes it basically unusable.

![image](https://github.com/denoland/vscode_deno/assets/7539725/8796ae07-8e2a-42f7-9cf0-85dce995ce95)

**Comment by dsherret** [comment]
I tried this and it works fine for me:

![image](https://github.com/denoland/vscode_deno/assets/1609021/ee3c636d-cb28-4e44-9ccd-f935b1d1b1f4)

This may have been a temporary issue with esm.sh and might be related to https://github.com/denoland/fresh/issues/1420 -- Can you try running the following if using fresh?

```
deno run -A -r --watch=static/,routes/ dev.ts
```

If that doesn't work, are there any other details you can provide? Do you have any errors in the output window (View -> Output -> Select "Deno Language Server" in the drop down)?

@mazniak that is an issue with the esm.sh/stripe module. It's because of https://github.com/stripe/stripe-node/issues/1636 -- the npm specifier handles it, but currently esm.sh does not.

@deckchairlabs if you get the chance, please open a specific issue outlining the problem. I'm not sure how to reproduce that screenshot because I don't know what those bare specifiers map to. Also, try running...

```
deno check -r --all your_script_goes_here.ts
````

...then see if there are any type checking errors. Running with `deno check --all` on the command line is a good way to diagnose type checking issues because it will type check everything including remote modules.

**Comment by deckchairlabs** [comment]
> I tried this and it works fine for me:
> 
> ![image](https://user-images.githubusercontent.com/1609021/253423859-ee3c636d-cb28-4e44-9ccd-f935b1d1b1f4.png)
> 
> This may have been a temporary issue with esm.sh and might be related to [denoland/fresh#1420](https://github.com/denoland/fresh/issues/1420) -- Can you try running the following if using fresh?
> 
> ```
> deno run -A -r --watch=static/,routes/ dev.ts
> ```
> 
> If that doesn't work, are there any other details you can provide? Do you have any errors in the output window (View -> Output -> Select "Deno Language Server" in the drop down)?
> 
> @mazniak that is an issue with the esm.sh/stripe module. It's because of [stripe/stripe-node#1636](https://github.com/stripe/stripe-node/issues/1636) -- the npm specifier handles it, but currently esm.sh does not.
> 
> @deckchairlabs if you get the chance, please open a specific issue outlining the problem. I'm not sure how to reproduce that screenshot because I don't know what those bare specifiers map to. Also, try running...
> 
> ```
> deno check -r --all your_script_goes_here.ts
> ```
> 
> ...then see if there are any type checking errors. Running with `deno check --all` on the command line is a good way to diagnose type checking issues because it will type check everything including remote modules.

Yeah does seem to be an issue on my end, theres no way to run `check` and it spits out all the type definitions loaded? Or run an `info` and try and find the culprit that way?

**Comment by rgripper** [comment]
I'll only be able to check next Friday

**Comment by rgripper** [comment]
I reloaded deno cache and all types are picked up now👍
