### ISSUE TITLE
Confusing use of the term ‘built-in’?

### ISSUE THREAD

**Issue by shelby3** [denoland/vscode_deno#96]
https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
https://github.com/denoland/vscode_deno

> This extension works using VS Code's **built-in version** of TypeScript.

What is that?

```
built-in
/ˌbiltˈin/
adjective
adjective: built-in

    forming an integral part of a structure or device.
    "a camera with a built-in zoom lens"
```

I read here:

https://code.visualstudio.com/docs/typescript/typescript-tutorial

> Visual Studio Code includes TypeScript language support but does not include the TypeScript compiler, `tsc`. You will need to install the TypeScript compiler either globally or in your workspace to transpile TypeScript source code to JavaScript (`tsc HelloWorld.ts`).

Could someone edit the terminology to say _“the version of TypeScript installed for VS Code globally”_ or otherwise provide a less confusing statement? Or is the TypeScript compiler really built-in to VS Code contrary to the documentation?

EDIT: I wouldn’t know how to make the edit, nor would I feel comfortable proposing such a pull request given I am not involved in this project. I could possibly be misunderstanding something?

**Comment by David-Else** [comment]
I am sure it refers to the TypeScript language service that is built into VS Code, not the actual `tsc` compiler that is not. The `.README` is out of date and not great.

https://github.com/microsoft/TypeScript/wiki/Architectural-Overview
How about:
>This extension works using VS Code's built-in version of TypeScript.

Becomes:

>This extension works using Visual Studio Code's built-in TypeScript language service.

**Comment by hsiaosiyuan0** [comment]
perhaps it's not even related that I find there maybe a little bit more lighter implementation of this extension - just generating or updating the `.vscode/settings.json` under the working workspace and fixing the desired options in that file since I find typescript-language-features will take account of other extensions' `contributes.typescriptServerPlugins` so after specificing
deno plugin [here](https://github.com/denoland/vscode_deno/blob/master/package.json#L45) only the tssdk location is the problem

**Comment by lucacasonato** [comment]
Resolved in version 3.x of the extension.
